export interface ReportDefinition {
  id: string;
  name: string;
  module: string;
  category: string;
  description: string;
  filters: string[];
  columns: { key: string; label: string; align?: 'right' | 'left' | 'center'; format?: string }[];
  dataSourceUrl: string;
  permissions: string[];
  printTemplate: 'A4_PORTRAIT' | 'A4_LANDSCAPE';
  exportFormats: string[];
}

export const REPORT_CATEGORIES = [
  { id: 'ACCOUNTING', name: 'التقارير المحاسبية', icon: 'BookOpen' },
  { id: 'FINANCIAL', name: 'التقارير المالية الختامية', icon: 'Scale' },
  { id: 'SALES', name: 'تقارير المبيعات', icon: 'TrendingUp' },
  { id: 'CUSTOMERS', name: 'تقارير العملاء', icon: 'Users' },
  { id: 'PURCHASING', name: 'تقارير المشتريات', icon: 'ShoppingCart' },
  { id: 'SUPPLIERS', name: 'تقارير الموردين', icon: 'Truck' },
  { id: 'INVENTORY', name: 'تقارير المخزون', icon: 'Package' },
  { id: 'CASH', name: 'تقارير النقدية والصناديق', icon: 'Wallet' },
  { id: 'BANKING', name: 'تقارير البنوك والتسوية', icon: 'Building' },
  { id: 'ASSETS', name: 'تقارير الأصول الثابتة', icon: 'Layers' },
  { id: 'EXPENSES', name: 'تقارير المصروفات', icon: 'Receipt' },
  { id: 'TAX', name: 'التقارير الضريبية', icon: 'FileText' },
  { id: 'MANAGEMENT', name: 'التقارير التنفيذية والإدارة', icon: 'BarChart' },
  { id: 'AUDIT', name: 'تقارير التدقيق والأمان', icon: 'ShieldCheck' },
];

export const REPORT_REGISTRY: ReportDefinition[] = [
  // 1. ACCOUNTING
  {
    id: 'general-ledger',
    name: 'دفتر الأستاذ العام',
    module: 'ACCOUNTING',
    category: 'ACCOUNTING',
    description: 'عرض تفصيلي لجميع الحركات والقيود المرحّلة على حساب مالي محدد مع الرصيد التراكمي المستمر.',
    filters: ['dateRange', 'branch', 'account'],
    columns: [
      { key: 'entryNumber', label: 'رقم القيد' },
      { key: 'entryDate', label: 'التاريخ' },
      { key: 'description', label: 'البيان' },
      { key: 'debit', label: 'مدين', format: 'currency' },
      { key: 'credit', label: 'دائن', format: 'currency' },
      { key: 'balance', label: 'الرصيد', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/general-ledger',
    permissions: ['reports.view', 'reports.financial.view'],
    printTemplate: 'A4_PORTRAIT',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },
  {
    id: 'trial-balance',
    name: 'ميزان المراجعة',
    module: 'ACCOUNTING',
    category: 'ACCOUNTING',
    description: 'عرض أرصدة وحركات جميع حسابات دليل الحسابات للمراجعة والتحقق من تساوي المدين والدائن.',
    filters: ['dateRange', 'branch', 'fiscalYear'],
    columns: [
      { key: 'accountCode', label: 'كود الحساب' },
      { key: 'accountName', label: 'اسم الحساب' },
      { key: 'openingDebit', label: 'افتتاحي مدين', format: 'currency' },
      { key: 'openingCredit', label: 'افتتاحي دائن', format: 'currency' },
      { key: 'periodDebit', label: 'حركة مدين', format: 'currency' },
      { key: 'periodCredit', label: 'حركة دائن', format: 'currency' },
      { key: 'closingDebit', label: 'ختامي مدين', format: 'currency' },
      { key: 'closingCredit', label: 'ختامي دائن', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/trial-balance',
    permissions: ['reports.view', 'reports.financial.view'],
    printTemplate: 'A4_LANDSCAPE',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },
  {
    id: 'journal-entries',
    name: 'تقرير قيود اليومية',
    module: 'ACCOUNTING',
    category: 'ACCOUNTING',
    description: 'سجل شامل لجميع قيود اليومية المسجلة في النظام مع تفاصيل الحسابات وأطراف القيد.',
    filters: ['dateRange', 'branch'],
    columns: [
      { key: 'entryNumber', label: 'رقم القيد' },
      { key: 'date', label: 'التاريخ' },
      { key: 'description', label: 'البيان' },
      { key: 'status', label: 'الحالة' },
      { key: 'totalAmount', label: 'المبلغ', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/general-ledger',
    permissions: ['reports.view', 'reports.financial.view'],
    printTemplate: 'A4_LANDSCAPE',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },
  {
    id: 'account-activity',
    name: 'حركة الحسابات المالية',
    module: 'ACCOUNTING',
    category: 'ACCOUNTING',
    description: 'ملخص الحركات المدينة والدائنة وصافي الحركة لكل حساب خلال الفترة المحددة.',
    filters: ['dateRange', 'branch'],
    columns: [
      { key: 'accountCode', label: 'كود الحساب' },
      { key: 'accountName', label: 'اسم الحساب' },
      { key: 'totalDebit', label: 'إجمالي المدين', format: 'currency' },
      { key: 'totalCredit', label: 'إجمالي الدائن', format: 'currency' },
      { key: 'netChange', label: 'صافي الحركة', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/trial-balance',
    permissions: ['reports.view', 'reports.financial.view'],
    printTemplate: 'A4_PORTRAIT',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },

  // 2. FINANCIAL
  {
    id: 'income-statement',
    name: 'قائمة الدخل (الأرباح والخسائر)',
    module: 'FINANCIAL',
    category: 'FINANCIAL',
    description: 'تقرير الأداء المالي الشامل يوضح الإيرادات، تكلفة البضاعة المباعة، مجمل الربح، والمصروفات.',
    filters: ['dateRange', 'branch', 'fiscalYear'],
    columns: [
      { key: 'category', label: 'البند / الحساب' },
      { key: 'amount', label: 'المبلغ (YER)', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/income-statement',
    permissions: ['reports.view', 'reports.financial.view'],
    printTemplate: 'A4_PORTRAIT',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },
  {
    id: 'balance-sheet',
    name: 'الميزانية العمومية (المركز المالي)',
    module: 'FINANCIAL',
    category: 'FINANCIAL',
    description: 'عرض الأصول، الالتزامات، وحقوق الملكية في تاريخ محدد وفق المعادلة المحاسبية.',
    filters: ['dateRange', 'branch'],
    columns: [
      { key: 'item', label: 'العنصر المالي' },
      { key: 'balance', label: 'الرصيد (YER)', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/balance-sheet',
    permissions: ['reports.view', 'reports.financial.view'],
    printTemplate: 'A4_PORTRAIT',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },
  {
    id: 'cash-flow',
    name: 'قائمة التدفقات النقدية',
    module: 'FINANCIAL',
    category: 'FINANCIAL',
    description: 'تحليل التدفقات النقدية من الأنشطة التشغيلية، الاستثمارية، والتمويلية.',
    filters: ['dateRange', 'branch'],
    columns: [
      { key: 'activity', label: 'النشاط' },
      { key: 'netCash', label: 'صافي التدفق (YER)', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/cash-flow',
    permissions: ['reports.view', 'reports.financial.view'],
    printTemplate: 'A4_PORTRAIT',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },
  {
    id: 'profitability-analysis',
    name: 'تحليل الربحية والأداء',
    module: 'FINANCIAL',
    category: 'FINANCIAL',
    description: 'نسب تحليل الربحية وهامش مجمل الربح وصافي الربح التشغيلي.',
    filters: ['dateRange', 'branch'],
    columns: [
      { key: 'metric', label: 'مؤشر الأداء' },
      { key: 'value', label: 'القيمة / النسبة' },
    ],
    dataSourceUrl: '/api/reports/income-statement',
    permissions: ['reports.view', 'reports.financial.view'],
    printTemplate: 'A4_PORTRAIT',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },

  // 3. SALES
  {
    id: 'sales-summary',
    name: 'ملخص فواتير المبيعات',
    module: 'SALES',
    category: 'SALES',
    description: 'إجمالي المبيعات، الضرائب، والخصومات والتحصيلات لفواتير المبيعات المرحّلة.',
    filters: ['dateRange', 'branch'],
    columns: [
      { key: 'invoiceNumber', label: 'رقم الفاتورة' },
      { key: 'date', label: 'التاريخ' },
      { key: 'customerName', label: 'العميل' },
      { key: 'subtotal', label: 'المبلغ', format: 'currency' },
      { key: 'tax', label: 'الضريبة', format: 'currency' },
      { key: 'total', label: 'الإجمالي', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/general-ledger',
    permissions: ['reports.view', 'reports.sales.view'],
    printTemplate: 'A4_LANDSCAPE',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },
  {
    id: 'sales-returns',
    name: 'مردودات المبيعات',
    module: 'SALES',
    category: 'SALES',
    description: 'تقرير بمرتجعات المبيعات والأرصدة الدائنة الصادرة للعملاء.',
    filters: ['dateRange', 'branch'],
    columns: [
      { key: 'returnNumber', label: 'رقم المرتجع' },
      { key: 'date', label: 'التاريخ' },
      { key: 'customerName', label: 'العميل' },
      { key: 'amount', label: 'المبلغ', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/general-ledger',
    permissions: ['reports.view', 'reports.sales.view'],
    printTemplate: 'A4_PORTRAIT',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },

  // 4. CUSTOMERS
  {
    id: 'customer-statement',
    name: 'كشف حساب العملاء',
    module: 'SALES',
    category: 'CUSTOMERS',
    description: 'حركة الفواتير والسندات والأرصدة للعملاء خلال الفترة.',
    filters: ['dateRange', 'customer', 'branch'],
    columns: [
      { key: 'date', label: 'التاريخ' },
      { key: 'reference', label: 'رقم المستند' },
      { key: 'description', label: 'البيان' },
      { key: 'debit', label: 'مدين', format: 'currency' },
      { key: 'credit', label: 'دائن', format: 'currency' },
      { key: 'balance', label: 'الرصيد', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/customer-statement',
    permissions: ['reports.view', 'reports.sales.view'],
    printTemplate: 'A4_PORTRAIT',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },
  {
    id: 'ar-aging',
    name: 'أعمار ديون العملاء (AR Aging)',
    module: 'SALES',
    category: 'CUSTOMERS',
    description: 'تحليل أرصدة الذمم المدينة حسب فترات التأخير (1-30، 31-60، 61-90، وأكثر من 90 يوم).',
    filters: ['branch'],
    columns: [
      { key: 'customerName', label: 'اسم العميل' },
      { key: 'current', label: 'جاري', format: 'currency' },
      { key: 'days30', label: '1-30 يوم', format: 'currency' },
      { key: 'days60', label: '31-60 يوم', format: 'currency' },
      { key: 'days90', label: '61-90 يوم', format: 'currency' },
      { key: 'over90', label: 'أكثر من 90 يوم', format: 'currency' },
      { key: 'total', label: 'الإجمالي', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/accounts-receivable',
    permissions: ['reports.view', 'reports.sales.view'],
    printTemplate: 'A4_LANDSCAPE',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },

  // 5. PURCHASING
  {
    id: 'purchase-summary',
    name: 'ملخص فواتير الشراء',
    module: 'PURCHASING',
    category: 'PURCHASING',
    description: 'إجمالي المشتريات، الضرائب، والمستحقات لفواتير الشراء.',
    filters: ['dateRange', 'branch'],
    columns: [
      { key: 'invoiceNumber', label: 'رقم الفاتورة' },
      { key: 'date', label: 'التاريخ' },
      { key: 'supplierName', label: 'المورد' },
      { key: 'total', label: 'الإجمالي', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/general-ledger',
    permissions: ['reports.view', 'reports.purchases.view'],
    printTemplate: 'A4_LANDSCAPE',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },

  // 6. SUPPLIERS
  {
    id: 'supplier-statement',
    name: 'كشف حساب الموردين',
    module: 'PURCHASING',
    category: 'SUPPLIERS',
    description: 'حركة فواتير الشراء وسندات الصرف والأرصدة للموردين.',
    filters: ['dateRange', 'supplier', 'branch'],
    columns: [
      { key: 'date', label: 'التاريخ' },
      { key: 'reference', label: 'رقم المستند' },
      { key: 'description', label: 'البيان' },
      { key: 'debit', label: 'مدين', format: 'currency' },
      { key: 'credit', label: 'دائن', format: 'currency' },
      { key: 'balance', label: 'الرصيد', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/supplier-statement',
    permissions: ['reports.view', 'reports.sales.view'],
    printTemplate: 'A4_PORTRAIT',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },
  {
    id: 'ap-aging',
    name: 'أعمار ديون الموردين (AP Aging)',
    module: 'PURCHASING',
    category: 'SUPPLIERS',
    description: 'تحليل الالتزامات المستحقة للموردين حسب فترات الاستحقاق.',
    filters: ['branch'],
    columns: [
      { key: 'supplierName', label: 'اسم المورد' },
      { key: 'current', label: 'جاري', format: 'currency' },
      { key: 'days30', label: '1-30 يوم', format: 'currency' },
      { key: 'days60', label: '31-60 يوم', format: 'currency' },
      { key: 'days90', label: '61-90 يوم', format: 'currency' },
      { key: 'over90', label: 'أكثر من 90 يوم', format: 'currency' },
      { key: 'total', label: 'الإجمالي', format: 'currency' },
    ],
    dataSourceUrl: '/api/reports/accounts-payable-aging',
    permissions: ['reports.view', 'reports.sales.view'],
    printTemplate: 'A4_LANDSCAPE',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },

  // 7. INVENTORY
  {
    id: 'inventory-valuation',
    name: 'تقييم المخزون (WAC Valuation)',
    module: 'INVENTORY',
    category: 'INVENTORY',
    description: 'أرصدة الأصناف الحالية في المستودعات مع تقييم التكلفة بناءً على المتوسط المرجح.',
    filters: ['warehouse', 'item'],
    columns: [
      { key: 'itemCode', label: 'كود الصنف' },
      { key: 'itemName', label: 'اسم الصنف' },
      { key: 'warehouseName', label: 'المستودع' },
      { key: 'quantity', label: 'الرصيد المتاح', format: 'number' },
      { key: 'averageCost', label: 'متوسط التكلفة', format: 'currency' },
      { key: 'totalValue', label: 'إجمالي التقييم', format: 'currency' },
    ],
    dataSourceUrl: '/api/inventory/reports/value',
    permissions: ['reports.view', 'reports.inventory.view'],
    printTemplate: 'A4_PORTRAIT',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },
  {
    id: 'low-stock',
    name: 'الأصناف منخفضة المخزون',
    module: 'INVENTORY',
    category: 'INVENTORY',
    description: 'الأصناف التي اقتربت أرصدتها من حد إعادة الطلب.',
    filters: ['warehouse'],
    columns: [
      { key: 'sku', label: 'كود الصنف' },
      { key: 'name', label: 'اسم الصنف' },
      { key: 'qty', label: 'الرصيد الحالي' },
      { key: 'threshold', label: 'حد الطلب' },
    ],
    dataSourceUrl: '/api/inventory/reports/value',
    permissions: ['reports.view', 'reports.inventory.view'],
    printTemplate: 'A4_PORTRAIT',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },

  // 8. CASH & 9. BANKING & 10. ASSETS & 11. EXPENSES & 12. TAX & 14. AUDIT
  {
    id: 'audit-logs',
    name: 'سجل التدقيق والأمان',
    module: 'AUDIT',
    category: 'AUDIT',
    description: 'سجل إثبات الأنشطة والعمليات الحساسة في النظام مع اسم المستخدم ووقت التنفيذ.',
    filters: ['dateRange', 'status'],
    columns: [
      { key: 'timestamp', label: 'وقت التنفيذ' },
      { key: 'username', label: 'المستخدم' },
      { key: 'action', label: 'العملية' },
      { key: 'entityType', label: 'نوع الكيان' },
      { key: 'ipAddress', label: 'عنوان IP' },
    ],
    dataSourceUrl: '/api/audit-logs?limit=100',
    permissions: ['reports.view', 'reports.audit.view'],
    printTemplate: 'A4_LANDSCAPE',
    exportFormats: ['PDF', 'XLSX', 'CSV', 'PRINT'],
  },
];
